name: String inverter Build

on:
    workflow_dispatch:
    push:
      branches: [main]
    pull_request:
      branches: [main]

jobs:
  string-inverter-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
           python-version: 3.8

      - name: Install requirements
        run: |
            pip install -r requirements.txt

      - name: Run tests
        run: |
            python -m pytest --junit-xml test-results.xml

      - name: Post test results
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          # A list of JUnit XML files, directories containing the former, and wildcard
          # patterns to process.
          # See @actions/glob for supported patterns.
          path: test-results.xml
      
          # Add a summary of the results at the top of the report
          # Default: true
          summary: true
      
          # Select which results should be included in the report.
          # Follows the same syntax as
          # `pytest -r`
          # Default: fEX
          display-options: fEX
      
          # Fail the workflow if no JUnit XML was found.
          # Default: true
          fail-on-empty: true